package com.michaeltchuang.walletsdk.core.railmpp.utils

object RailMppConstants {
    const val FUTURENET_MPP_SESSION_VAULT_APP_ID: Long = 17794007L
    const val FUTURENET_MPP_SESSION_VAULT_APP_ADDRESS = "XYDZ7A3PL2PSSM3FLATB2ZX5ACOCGMOQGHOS3S7HT2NYPOJ6K27NESS4XY"
    const val TESTNET_MPP_SESSION_VAULT_APP_ID: Long = 764929040L
    const val TESTNET_MPP_SESSION_VAULT_APP_ADDRESS = "5SA4TIRCE2Y7XVJS2ZNXMWIGXGB4R5DK43TPUNSJST5EXPVABIQRKWXU2U"
    const val MAINNET_MPP_SESSION_VAULT_APP_ID: Long = 3617483943L
    const val MAINNET_MPP_SESSION_VAULT_APP_ADDRESS = "26XC5GSRN42CGA4JTX5GQULHONBTWGHIABRY3R4L6ZI3YPXRZIPN3BXDMQ"

    const val MPP_SESSION_VAULT_APP_ID: Long = TESTNET_MPP_SESSION_VAULT_APP_ID
    const val MPP_SESSION_VAULT_APP_ADDRESS = TESTNET_MPP_SESSION_VAULT_APP_ADDRESS

    // Debug toggles for on-chain helper verification during voucher troubleshooting.
    const val ENABLE_VIEWER_DEBUG_VERIFY_HELPER_ON_CHAIN: Boolean = false
    const val ENABLE_CREATOR_DEBUG_VERIFY_HELPER_ON_CHAIN: Boolean = false
}
