package com.michaeltchuang.walletsdk.core.railmpp.utils

object RailMppConstants {
    const val FUTURENET_MPP_SESSION_VAULT_APP_ID: Long = 18086245L
    const val FUTURENET_MPP_SESSION_VAULT_APP_ADDRESS = "AGJFWTU2P5YWFRVMXTKXGFW4ELJK7VGBPQRUP6ZV66X7KZ6XENFEVNK36Q"
    const val TESTNET_MPP_SESSION_VAULT_APP_ID: Long = 770746572L
    const val TESTNET_MPP_SESSION_VAULT_APP_ADDRESS = "24DZUPT3BBAO7N7KY7OCGSFFCTVXMHUCOVP3WEEFZEEMKKOO3H4AZIPPVU"
    const val MAINNET_MPP_SESSION_VAULT_APP_ID: Long = 3689924545L
    const val MAINNET_MPP_SESSION_VAULT_APP_ADDRESS = "D3Q3EXWL7HSVSA6GMWUQLQTEPPWDDS3NN6GFZYT2UV2GN34PRIDBYHKEZE"

    const val MPP_SESSION_VAULT_APP_ID: Long = TESTNET_MPP_SESSION_VAULT_APP_ID
}
