name: "BrowserStack Instrumented Tests"

on:
  workflow_dispatch:
#  push:
#  pull_request_target:
#    types: [ opened, synchronize ]

env:
  GITHUB_TOKEN: ${{ github.token }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  browserstack:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v5

      - name: "Install JDK 21"
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "gradle"

      - name: "Create Debug APK and Test APK"
        run: |
          ./gradlew composeDemoApp:assembleDebug
          ./gradlew composeDemoApp:assembleDebugAndroidTest

      - name: "Upload and Run Tests on BrowserStack"
        id: browserstack
        uses: chrisbanes/browserstack-android-action@v0.0.1
        with:
          browserstackUsername: ${{ secrets.BROWSERSTACK_USERNAME }}
          browserstackAccessKey: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          project: AlgoKit-WalletSDK-KMP
          buildTag: ${{ github.sha }}
          appFilePath: ${{ github.workspace }}/composeDemoApp/build/outputs/apk/debug/composeDemoApp-debug.apk
          testFilePath: ${{ github.workspace }}/composeDemoApp/build/outputs/apk/androidTest/debug/composeDemoApp-debug-androidTest.apk
          devices: Samsung Galaxy S24-14.0

      - name: "Write to Json file"
        run: |
          mkdir -p ${{ github.workspace }}/composeDemoApp/build/reports/browserstack
          touch ${{ github.workspace }}/composeDemoApp/build/reports/browserstack/test-results.json
          echo '${{ env.test_result }}' > ${{ github.workspace }}/composeDemoApp/build/reports/browserstack/test-results.json

      - name: "Upload Test Results"
        uses: actions/upload-artifact@v5
        with:
          name: browserstack-test-results
          path: ${{ github.workspace }}/composeDemoApp/build/reports/browserstack/test-results.json
